[package]
name = "forever-billy"
version = "0.1.1"
authors = ["Bentley Holmes-Gull <bholmes-gull@nshe.nevada.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"